/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tom' at '16-7-19 上午6:49' with Gradle 2.11
 *
 * @author tom, @date 16-7-19 上午6:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
